name: Lint

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CACHE_TIMEOUT_MINUTES: 5
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: sccache
  CC: sccache clang
  CXX: sccache clang++

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          toolchain: stable
          override: false
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11
        timeout-minutes: "${{ fromJSON(env.CACHE_TIMEOUT_MINUTES) }}"
        continue-on-error: true
      - uses: actions/checkout@v7
      - name: Apt Dependencies
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            sudo apt-get install -y libclang-dev # required dep for cargo-spellcheck
      - uses: jdx/mise-action@v4
      - run: mise run lint:install-tools
      - run: mise run lint
